### ISSUE TITLE
Doublequotes in string field

### ISSUE THREAD

**Issue by Sciator** [influxdata/influxdb-client-dart#45]
**Describe the bug**
Writing string from dart containing
```
[{"measurement":"Temperature","label":"Temperature","unit":"°C"...
```
results in this string in influxdb
```
[{\measurement\:\Temperature\,\label\:\Temperature\,\unit\:\°C\...
```

**Expected behavior**
Returned string from query will be same as written one

**Specifications:**
 - Client Version: main-git
 - InfluxDB Version: 2.0.9
 - Platform: Win/Android

**Comment by bednar** [comment]
Hi @Sciator,

thanks for using our client.

I've prepared a fixed version within #46.  The stable version of the client will be available in regular release cycle.
If you would like to use the development version, then you can import the library by:

```
dependencies:
  influxdb_client:
    git:
      url: git@github.com:influxdata/influxdb-client-dart.git
      ref: fix_string_serialization
```

- https://dart.dev/tools/pub/dependencies#git-packages

Regards
